FROM python:3.9-slim

WORKDIR /app

# Agregar usuario seguro
RUN groupadd -g 3000 app && useradd -m -u 10001 -g 3000 --no-log-init app

# Copiar e instalar dependencias con caching para evitar instalaciones repetitivas
COPY requirements.txt .
COPY requirements-dev.txt .
RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

# Copiar el código fuente y las pruebas
COPY src /app/src
COPY tests /app/tests

# Definir el path de Python para que pytest reconozca el código
ENV PYTHONPATH=/app/src

# Cambiar permisos para evitar problemas de acceso a archivos
RUN chown -R app:app /app
USER app

# CMD mejorado con reportes y salida más detallada en CI/CD
CMD ["sh", "-c", "PYTHONPATH=/app/src pytest --emoji -v --color=yes"]